E2137. Fix view in student_task/list page
unjalli/expertiza pull request #5
Opened 2021-10-20 01:18 UTC by unjalli

Changes proposed in this pull request:
- Add "submission grade column"
- Write tests for checking that the new column has correct information
- Team responsible fo reviewing the changes: Team Wolfpack

2021-10-20 15:49 UTC, subodhthota97 requested changes

2021-10-20 15:49 UTC, subodhthota97 commented on Gemfile
> +gem 'airbrake', '~> 9.5'
I think these changes should be undone, because these  gemfile changes are not needed by everyone.

2021-10-20 23:05 UTC, unjalli commented on Gemfile
> +gem 'airbrake', '~> 9.5'
I will undo these changes for the final PR to expertiza->expertiza. For now I cannot undo these changes as this will cause errors in the local system.

2021-10-21 00:13 UTC, subodhthota97 approved these changes

2021-10-21 01:14 UTC, merged